swagger: '2.0'
host: soshealth.in
basePath: /booking-management/v1
schemes:
  - https
  - http
consumes:
  - application/json
produces:
  - application/json
paths:
  /booking:
   
    post:
      operationId: createBooking
      tags:
        - Booking Management
      description: Create Booking from Customer side as Inprogress
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: Booking Input
          required: true
          schema:
            $ref: '#/definitions/BookingInput'
      responses:
        '200':
          description: |
            *OK* - Inserted Service Provider Will be returned Successfully
          schema:
            $ref: '#/definitions/BookingDetails'
        '400':
          description: |
            *Error* - Bad Request
          schema:
            $ref: '#/definitions/Error'
        '404':
          description: |
            *Error* - Not Found
          schema:
            $ref: '#/definitions/Error'
        '500':
          description: |
            *Error* - Internal Server error
          schema:
            $ref: '#/definitions/Error'
    
 

definitions:
  Error:
    type: object
    properties:
      status:
        type: string
        description: |
          Status of the Error
      messgae:
        type: string
        description: |
          It will contain detailed message for the Error
          
  BookingStatus:
    type: string
    enum:
      - COMPLETED
      - INPROGRESS
      - CANCELLED
      - SERVED
      - REFUND_INIT
      - REFUND_COMPLETE
  
  PaymentMode:
    type: string
    enum:
      - Online
      - COD
      - NotSelected
      
  AddressRef:
    type: object
    properties:
      street1:
        type: string
        description: |
          Street 1 of Organization
      street2:
        type: string
        description: |
          Street 2 of Organization
      country:
        type: string
        description: |
          Country of the organizaton
      state:
        type: string
        description: |
          State where its Situated
      zipcode:
        type: string
        description: |
          Zipcode for the organization
          
  CustomerRef:
    type: object
    properties:
      id:
        type: string
        description: |
          Customer ID will be populated
      fullName:
        type: string
        description: |
          Full Name of the Customer
          
  ServiceProviderRef:
    type: object
    properties:
      id:
        type: string
        description: |
          Service Provider ID
      qualification:
        type: string
        description: |
          Qualification of a Service Provider
      fee:
        type: integer
        description: |
          Fees of Service provider
        
  BookingDetails:
    type: object
    properties:
      id: 
        type: string
        description: | 
          Booking ID must unique
      deviceId: 
        type: string
        description: | 
          From which Device this booking is been made
      bookingDate:
        type: string
        description: |
          Booking Date Must be populated
      bookingOTP: 
        type: integer
        description: |
          This OTP must be Booking OTP which needs to be validated before Servicing
      serviceProvider:
        $ref: '#/definitions/ServiceProviderRef'
      customer:
        $ref: '#/definitions/CustomerRef'
      serviceAddress:
        $ref: '#/definitions/AddressRef'
      bookingStatus:
        $ref: '#/definitions/BookingStatus'
      serviceStatus:
        $ref: '#/definitions/ServiceStatus'
      paymentId:
        type: string
        description: | 
          Payment / Transaction ID
      paymentMode:
        $ref: '#/definitions/PaymentMode'
          
  BookingInput:
    type: object
    properties:
      deviceId: 
        type: string
        description: | 
          From which Device this booking is been made
      serviceProviderId:
        type: string
        description: |
          Service Provider Id
      customerId: 
        type : string
        description: |
          Customer ID for booking
      serviceAddress:
        $ref: '#/definitions/AddressRef'
      bookingStatus:
        $ref: '#/definitions/BookingStatus'
      serviceStatus:
        $ref: '#/definitions/ServiceStatus'
      
  ServiceStatus:
    type: string
    enum:
      - COMPLETED
      - DECLINED
      - ACCEPTED
      - INTRANSIT
      
