swagger: '2.0'
host: soshealth.in
basePath: /price-management/v1
schemes:
  - https
  - http
consumes:
  - application/json
produces:
  - application/json
paths:
  /pricing:
   
    post:
      operationId: createPricing
      tags:
        - Price Management
      description: Create Pricing for Service Provider
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: Price Input
          required: true
          schema:
            $ref: '#/definitions/PriceInput'
      responses:
        '200':
          description: |
            *OK* - Inserted Pricing Details Will be returned Successfully
          schema:
            $ref: '#/definitions/Price'
        '400':
          description: |
            *Error* - Bad Request
          schema:
            $ref: '#/definitions/Error'
        '404':
          description: |
            *Error* - Not Found
          schema:
            $ref: '#/definitions/Error'
        '500':
          description: |
            *Error* - Internal Server error
          schema:
            $ref: '#/definitions/Error'
  
      
definitions:
  PriceInput:
    type: object
    properties:
      id: 
        type: string
        description: |
          Price Id would be primary key for Price table and same as Provider's Id
      actualPrice:
        $ref: '#/definitions/Amount'
      deductionRate:
        type: number
        description: |
          Rate on which actual and Customer price will be deducted
      taxRate:
        type: number
        description: |
          Rate on which TDS will be deducted
    
  Error:
    type: object
    properties:
      status:
        type: string
        description: |
          Status of the Error
      messgae:
        type: string
        description: |
          It will contain detailed message for the Error
          
  TransactionHistory:
    type: object
    properties:
      id:
        type: string
        description: |
          Transaction ID fro each Transaction to be done
      recipientId:
        type: string
        description: | 
          Transaction Recipient Id - Typically Service Provider ID
      senderId:
        type: string
        description: |
          Typically End user's Id - Customer Id
      transactionAmount:
        $ref: '#/definitions/Amount'
      transactionDate:
        type: string
        description: |
          On which Date Transaction Happened
      transactionStatus:
        type: string
        description: |
          Transaction Status would be filter parameter
      transactionMode:
        $ref: '#/definitions/TransactionMode'
  
  TransactionMode:
    type: string
    enum:
    - ONLINE
    - COD
    
  Price:
    allOf:
      - $ref: '#/definitions/PriceInput'
      - type: object
        properties:
          customerPrice:
            $ref: '#/definitions/Amount'
          taxAmount:
            $ref: '#/definitions/Amount'
          taxDeductedServiceCharge:
            $ref: '#/definitions/Amount'
        
  Amount:
    type: object
    properties:
      unit:
        type: string
        description: |
          Price Amount Unit | INR , Dollar , Euro
      value:
        type: string
        description: | 
          Value of object
         